import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    clearMocks: true,
    coverage: {
      include: ["src/**"],
      exclude: [
        "src/**/*.d.ts",
        "src/**/*.stories.tsx",

        // Remove these as coverage is added
        "src/app/page.tsx",
        "src/shared/enums/measurement-system.enum.ts",
        "src/shared/enums/length-unit.enum.ts",
        "src/app/loading.tsx",
        "src/middleware.ts",
        "src/app/manifest.ts",
        "src/shared/enums/weight-unit.enum.ts",
        "src/app/error.tsx",
        "src/app/layout.tsx",
        "src/shared/enums/breakpoint.enum.ts",
        "src/shared/errors/error-with-code.type.ts",
        "src/shared/database/db.ts",
        "src/features/auth/get-auth-session-details.util.ts",
        "src/app/\\(app\\)/layout.tsx",
        "src/shared/utils/validation/validate-email-address.util.ts",
        "src/app/fonts/fonts.ts",
        "src/shared/utils/validation/validate-measurement-system.util.ts",
        "src/shared/utils/math/round-to-decimal-places.util.ts",
        "src/shared/utils/units/convert-length-units.ts",
        "src/features/body-comp/calculate-body-fat.util.ts",
        "src/shared/utils/validation/validate-sex.util.ts",
        "src/shared/utils/units/convert-weight-units.ts",
        "src/shared/utils/dates/format-date-without-time.util.ts",
        "src/shared/utils/dates/get-age-from-birthday.util.ts",
        "src/shared/utils/math/calculate-sum.util.ts",
        "src/shared/utils/formatting/format-percent.util.ts",
        "src/shared/utils/math/calculate-average.util.ts",
        "src/shared/utils/formatting/use-formatted-weight.hook.ts",
        "src/shared/utils/dates/format-date-relative-to-today.util.ts",
        "src/shared/state/user-settings/user-settings.state.tsx",
        "src/features/body-comp/overview/overview-section.component.tsx",
        "src/features/body-comp/profile/user-profile-form.component.tsx",
        "src/shared/components/loading-indicator/loading-indicator.component.tsx",
        "src/shared/components/icon/icon.component.tsx",
        "src/features/body-comp/overview/overview-skinfold-section.component.tsx",
        "src/shared/components/heading/heading.component.tsx",
        "src/shared/components/header/header.component.tsx",
        "src/features/body-comp/profile/parse-and-save-user-profile-form.util.ts",
        "src/shared/database/daos/user-profile.dao.ts",
        "src/features/body-comp/overview/overview-page-contents.component.tsx",
        "src/features/body-comp/overview/overview-metric-row.component.tsx",
        "src/features/body-comp/overview/overview-measuring-tape-section.component.tsx",
        "src/features/body-comp/nav/body-comp-nav.component.tsx",
        "src/features/body-comp/overview/overview-metrics-section.component.tsx",
        "src/features/body-comp/nav/body-comp-nav-button.component.tsx",
        "src/features/body-comp/overview/overview-condensed-item.component.tsx",
        "src/features/body-comp/body-comp-entry/body-comp-entry.dao.ts",
        "src/app/\\(onboarding\\)/welcome/page.tsx",
        "src/features/body-comp/body-comp-entry/body-comp-entry-details.component.tsx",
        "src/app/\\(onboarding\\)/onboarding/save-onboarding-information.action.tsx",
        "src/app/\\(onboarding\\)/onboarding/layout.tsx",
        "src/app/\\(onboarding\\)/onboarding/page.tsx",
        "src/shared/components/forms/select/option.component.tsx",
        "src/shared/components/header/header-button/header-button.component.tsx",
        "src/features/body-comp/log/list/body-comp-log-list.component.tsx",
        "src/shared/components/forms/select/select.component.tsx",
        "src/shared/components/forms/form-action-error-toast/form-action-error-toast.component.tsx",
        "src/shared/components/forms/input/input.component.tsx",
        "src/shared/components/buttons/floating-action-button/floating-action-button.component.tsx",
        "src/features/body-comp/log/list/body-comp-log-headers.component.tsx",
        "src/app/\\(app\\)/body-comp/\\(with-nav\\)/layout.tsx",
        "src/app/\\(app\\)/body-comp/new/page.tsx",
        "src/features/body-comp/log/body-comp-entry-form/process-body-comp-entry-form.action.ts",
        "src/features/body-comp/log/list/row/body-comp-log-row.component.tsx",
        "src/features/body-comp/log/list/row/body-comp-log-cell.component.tsx",
        "src/app/\\(app\\)/body-comp/\\[id\\]/edit/page.tsx",
        "src/features/body-comp/log/body-comp-entry-form/body-comp-entry-form.component.tsx",
        "src/app/\\(onboarding\\)/sign-in/\\[\\[...sign-in\\]\\]/page.tsx",
        "src/app/\\(app\\)/body-comp/\\[id\\]/page.tsx",
        "src/app/\\(app\\)/body-comp/\\[id\\]/edit/delete-body-comp-entry.action.ts",
        "src/app/\\(app\\)/body-comp/\\(with-nav\\)/profile/update-profile.action.ts",
        "src/app/\\(app\\)/body-comp/\\(with-nav\\)/log/page.tsx",
        "src/app/\\(app\\)/body-comp/\\(with-nav\\)/profile/page.tsx",
        "src/app/\\(app\\)/body-comp/\\(with-nav\\)/overview/page.tsx",
        "src/shared/utils/strings/get-ui-string.util.ts",
        "src/shared/utils/objects/typedObjectKeys.util.ts",
        "src/features/body-comp/body-comp-entry/load-body-comp-entries.action.ts",
        "src/shared/components/infinite-scroll-container/infinite-scroll-container.component.tsx",
      ],
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
        perFile: true,
        statements: 90,
      },
    },
    environment: "jsdom",
    include: ["src/**/*.test.ts?(x)"],
    setupFiles: ["src/testing/vitest/vitest-setup.ts"],
  },
});
